### PR TITLE
fix overlap on team member card| table view

### LINKED ISSUE #2991: [Improvement] Team member card | Table view
The issue is that in Team member card → Table view, elements overlap :

[Screencast from 2024-09-07 13-00-11.webm](https://github.com/user-attachments/assets/9f0514a1-5c43-40d0-97cd-812f8b5fa719)

### PR DESCRIPTION
**Pull request by CREDO23**
## Description

This PR fixes  #2991 

## Type of Change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change
-   [ ] Documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings

## Current screenshots

[Loom](https://www.loom.com/share/625a8009297543b487c1a5051b44d146)

### CODE REVIEW

File: apps/web/lib/features/team-member-cell.tsx [hunk 1]
```diff
@@ -38,24 +38,20 @@ export function UserInfoCell({ cell }: { cell: any }) {
...
 
 	return (
 		<TaskTimes
 			activeAuthTask={true}
 			memberInfo={memberInfo}
 			task={memberInfo.memberTask}
 			isAuthUser={memberInfo.isAuthUser}
-			className={clsxm(
-				'flex flex-col justify-center items-center mx-auto',
-				fullWidth ? '2xl:w-[7rem] 3xl:w-[11rem]' : '2xl:w-[7rem]  3xl:w-[10rem]'
```
Comment (evereq) [inline apps/web/lib/features/team-member-cell.tsx:57]: @CREDO23 so now it's not depend on fullWidth or not?
