### PR TITLE
set the tab to outstanding if there are outstanding tasks next day

### LINKED ISSUE #3066: [Bug] 'Planned' | Wrong tab is shown when user open own Profile
The issue is that when user has uncompleted tasks for the previous plans tab 'Outstanding', it should show that tab as default, but in reality it showed tab 'Unassigned'

**Potential reason**: A few days in a row observing cases with all members, when the user clicking on own or someone Profile page, the system has delay with updating real amount of tasks assigned/planned/unassigned to that particular member.
Regarding reason - potentially the system could think that in tab Outstanding '0' tasks, and it redirected to another tab.

Even now was able to see strange bug, was opened tab 'Outstanding'
Screenshot at Sep 25 08-27-39

in 1-2 minutes the same tab
Screenshot at Sep 25 08-27-16

After I went to another page and back to this, it was again the correct data as on the first picture

### PR DESCRIPTION
**Pull request by CREDO23**
## Description

This PR fixes #3066 

## Type of Change

-   [x] Bug fix
-   [ ] New feature
-   [ ] Breaking change
-   [ ] Documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings

### CODE REVIEW

File: apps/web/lib/features/task/task-filters.tsx [hunk 1]
```diff
@@ -172,20 +174,22 @@ export function useTaskFilter(profile: I_UserProfilePage) {
...
+					} else {
+						setTab('unassigned');
+					}
 				}
 			}
 		}
 
 		// eslint-disable-next-line react-hooks/exhaustive-deps
-	}, [dailyPlanSuggestionModalDate]);
+	}, []);
```
Comment (evereq) [inline apps/web/lib/features/task/task-filters.tsx:192]: @CREDO23 why empty array []? There are a lot of deps in the useEffect, e.g. `dailyPlanSuggestionModalDate`, todayPlan and more, do we need to add those?

**Comment by CREDO23** [comment]
> What is the status of this PR
> @CREDO23

The PR is ready to be reviewed @Cedric921 / @evereq

File: apps/web/lib/features/task/task-filters.tsx (hunk 1 above)
Comment (Cedric921) [reply apps/web/lib/features/task/task-filters.tsx:192]: Can you resolve this Comment Please 
@CREDO23
