### PR TITLE
[Refactor / Fix] Profile page | Update screenshot tab UI

### LINKED ISSUE #3399: [Refactor] Profile Page | Update Screenshot Tab UI
## Current version (implemeted in App) 

Screenshot 2024-12-05 at 13 49 43
Screenshot 2024-12-05 at 13 51 12

## New Design

Screenshot 2024-12-05 at 13 49 07
Screenshot 2024-12-05 at 13 50 41

### PR DESCRIPTION
**Pull request by CREDO23**
## Description

Fix #3399 

## Type of Change

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change
-   [ ] Documentation update

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented on my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings

## Current screenshots

[loom](https://www.loom.com/share/cb710c61968b413eba51826044648bc3?sid=4ed79941-ecaa-4f46-a73f-54c97a961ef3)

## Summary by CodeRabbit

Based on the comprehensive summary, here are the updated release notes:

- **New Features**
  - Added a segmented progress bar for enhanced visual representation of activity.
  - Introduced new view modes for screenshots.
  - Enhanced screenshot details modal with more comprehensive information.

- **Localization**
  - Added new translation keys for multiple languages, including view, client, and time log information.
  - Expanded localization support across 12 languages with additional keys for better user interaction.

- **UI/UX Improvements**
  - Updated screenshot item display with hover effects and additional interaction options.
  - Refined time slot and screenshot presentation.
  - Improved modal layouts and information display.

These changes focus on improving user experience, visual presentation, and multilingual support across the application.

### CODE REVIEW

File: apps/web/lib/features/activity/components/screenshot-details.tsx [hunk 1]
```diff
@@ -49,49 +73,74 @@ const ScreenshotDetailsModal = ({
...
+								</div>
+							</div>
+						</div>
+
+						{/* Project */}
+						<div className="w-full flex flex-col gap-2">
+							<p className="text-[#707070] font-medium">{t('pages.taskDetails.PROJECT')} : </p>
+							<div className="flex gap-1 ">
+								<div className="flex h-8 gap-2">
+									<div className=" w-8  h-full uppercase  rounded-sm flex items-center justify-center text-[1rem] bg-[#A5A4FF]">
```
Comment (Cedric921) [inline apps/web/lib/features/activity/components/screenshot-details.tsx:128]: Next work to Replace this **ET** by Project/Workspace Logo

File: apps/web/lib/features/activity/components/screenshot-details.tsx [hunk 2]
```diff
@@ -49,49 +73,74 @@ const ScreenshotDetailsModal = ({
...
+										ET
+									</div>
+									<div className=" h-full flex flex-col  justify-center gap-[.4rem]">
+										<p className=" font-xs leading-3 font-medium">Ever Teams</p>
```
Comment (Cedric921) [inline apps/web/lib/features/activity/components/screenshot-details.tsx:132]: Project Name should be dynamic, check if we can get it from TimeSlot data

**Review by Cedric921 — APPROVED** [review]
Data for This part should be also dynamic

Screenshot 2025-01-24 at 08 09 28

File: apps/web/lib/features/activity/components/screenshot-details.tsx (hunk 2 above)
Comment (CREDO23) [reply apps/web/lib/features/activity/components/screenshot-details.tsx:132]: sure @Cedric921 
i will have to check this (definetly from API responses, because, i can't find project information from the time slot interface

File: apps/web/lib/features/activity/components/screenshot-details.tsx (hunk 1 above)
Comment (CREDO23) [reply apps/web/lib/features/activity/components/screenshot-details.tsx:128]: sure @CREDO23 
i will have to check this (definetly from API responses)), because, i can't find project information from the time slot interface

Comment (Cedric921) [reply apps/web/lib/features/activity/components/screenshot-details.tsx:128]: okay, Issue created for this task [#3541](https://github.com/ever-co/ever-teams/issues/3541)

File: apps/web/lib/features/activity/components/screenshot-details.tsx (hunk 2 above)
Comment (Cedric921) [reply apps/web/lib/features/activity/components/screenshot-details.tsx:132]: okay, Issue created for this task https://github.com/ever-co/ever-teams/issues/3541
